name: 🐞 Bug Report
description: Report a bug

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Make sure Pony House is up to date.
        2. Make sure it's an issue with Pony House and not something else you are using.
        3. Remember to be friendly.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: info
    attributes:
      label: Platform and versions
      description: 'Provide OS, browser and Cinny version with your Homeserver.'
      placeholder: |
        1. OS: [e.g. Windows 10, MacOS]
        2. Browser: [e.g. chrome 99.5, firefox 97.2]
        3. Pony House version: [e.g. 1.8.1 (client.pony.house)]
        4. Matrix homeserver: [e.g. matrix.org]
      render: shell
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
